package com.mytest.bibliotecacomida

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.Toast
import com.mytest.bibliotecacomida.adapter.ItemArrayAdapter
import com.mytest.bibliotecacomida.modelos.Receta
import kotlinx.android.synthetic.main.activity_main.*
import android.content.Intent




class MainActivity : AppCompatActivity() {

    lateinit var adapterReceta:ItemArrayAdapter

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val datos = arrayOf(
            Receta("TChicken Spinoccoli","https://spoonacular.com/recipeImages/485365-556x370.jpg","https://www.olgasflavorfactory.com/recipes/main-course/poultry/chicken-spinoccoli-breaded-stuffed-chicken-breast-with-spinach-broccoli-and-cheese/","You can never have too many main course recipes, so give Chicken Spinoccoli – Breaded Stuffed Chicken Breast With Spinach, Broccoli and Cheese a try. One serving contains <b>610 calories</b>, <b>43g of protein</b>, and <b>32g of fat</b>. This recipe serves 4. For <b>\$3.17 per serving</b>, this recipe <b>covers 38%</b> of your daily requirements of vitamins and minerals. 646 people were impressed by this recipe. From preparation to the plate, this recipe takes around <b>1 hour and 5 minutes</b>. Head to the store and pick up mozzarella, wine, sun tomatoes, and a few other things to make it today. To use up the eggs you could follow this main course with the <a href=\"https://spoonacular.com/recipes/rose-levy-beranbaums-chocolate-tomato-cake-with-mystery-ganache-27408\">Rose Levy Beranbaum's Chocolate Tomato Cake with Mystery Ganache</a> as a dessert. All things considered, we decided this recipe <b>deserves a spoonacular score of 93%</b>. This score is amazing. Try <a href=\"https://spoonacular.com/recipes/breaded-chicken-breasts-stuffed-with-spinach-and-cheese-705644\">Breaded Chicken Breasts Stuffed with Spinach and Cheese</a>, <a href=\"https://spoonacular.com/recipes/cheese-and-broccoli-stuffed-chicken-breast-109979\">Cheese and Broccoli Stuffed Chicken Breast</a>, and <a href=\"https://spoonacular.com/recipes/broccoli-cheese-stuffed-chicken-breast-915534\">Broccoli Cheese Stuffed Chicken Breast</a> for similar recipes."),
            Receta("Imperial Chicken","https://spoonacular.com/recipeImages/74172-556x370.jpg","https://www.myrecipes.com/recipe/imperial-chicken","Imperial Chicken might be just the main course you are searching for. This recipe makes 12 servings with <b>431 calories</b>, <b>31g of protein</b>, and <b>21g of fat</b> each. For <b>\$1.58 per serving</b>, this recipe <b>covers 21%</b> of your daily requirements of vitamins and minerals. 1 person were impressed by this recipe. Head to the store and pick up garlic powder, butter, paprika, and a few other things to make it today. To use up the salt you could follow this main course with the <a href=\"https://spoonacular.com/recipes/apple-turnovers-recipe-48175\">Apple Turnovers Recipe</a> as a dessert. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. With a spoonacular <b>score of 54%</b>, this dish is pretty good. Try <a href=\"https://spoonacular.com/recipes/chicken-imperial-593221\">Chicken Imperial</a>, <a href=\"https://spoonacular.com/recipes/chicken-chow-mein-usa-version-imperial-9917\">Chicken Chow Mein (usa Version - Imperial)</a>, and <a href=\"https://spoonacular.com/recipes/chinese-imperial-palace-general-tsos-chicken-our-will-have-people-wondering-where-you-ordered-this-take-out-from-601255\">Chinese Imperial Palace General Tso’s Chicken our will have people wondering where you ordered this take out from</a> for similar recipes."),
            Receta("Chicken with Piquillos","https://spoonacular.com/recipeImages/74202-556x370.jpg","http://www.foodandwine.com/recipes/chicken-with-piquillos","You can never have too many main course recipes, so give Chicken with Piquillos a try. This caveman, gluten free, dairy free, and primal recipe serves 4 and costs <b>\$4.45 per serving</b>. One portion of this dish contains roughly <b>74g of protein</b>, <b>67g of fat</b>, and a total of <b>1002 calories</b>. 1 person found this recipe to be scrumptious and satisfying. A mixture of chicken, onion, piquillo peppers, and a handful of other ingredients are all it takes to make this recipe so tasty. To use up the dry white wine you could follow this main course with the <a href=\"https://spoonacular.com/recipes/white-wine-frozen-yogurt-206235\">White Wine Frozen Yogurt</a> as a dessert. From preparation to the plate, this recipe takes around <b>2 hours and 15 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 47%</b>. This score is solid. Try <a href=\"https://spoonacular.com/recipes/pimientos-piquillos-rellenos-de-bacalao-1874\">Pimientos Piquillos Rellenos De Bacalao</a>, <a href=\"https://spoonacular.com/recipes/queso-manchego-con-aceitunas-y-piquillos-230\">Queso Manchego con Aceitunas y Piquillos</a>, and <a href=\"https://spoonacular.com/recipes/speckled-trout-with-crab-stuffed-piquillos-edamame-and-truffle-vinaigrette-1589\">Speckled Trout with Crab-stuffed Piquillos, Edamame, and Truffle Vinaigrette</a> for similar recipes."),
            Receta("Chicken Cassoulet","https://spoonacular.com/recipeImages/94640-556x370.jpg","http://www.myrecipes.com/recipe/chicken-cassoulet-10000001585315/","Chicken Cassoulet might be just the main course you are searching for. One serving contains <b>528 calories</b>, <b>33g of protein</b>, and <b>25g of fat</b>. This recipe serves 8. For <b>\$1.65 per serving</b>, this recipe <b>covers 27%</b> of your daily requirements of vitamins and minerals. 1 person has made this recipe and would make it again. If you have flat-leaf parsley, celery, chicken broth, and a few other ingredients on hand, you can make it. To use up the onion you could follow this main course with the <a href=\"https://spoonacular.com/recipes/candy-corn-cupcakes-63881\">Candy Corn Cupcakes</a> as a dessert. From preparation to the plate, this recipe takes approximately <b>40 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 67%</b>. This score is solid. Try <a href=\"https://spoonacular.com/recipes/chicken-cassoulet-698796\">Chicken Cassoulet</a>, <a href=\"https://spoonacular.com/recipes/quick-chicken-cassoulet-75001\">Quick Chicken Cassoulet</a>, and <a href=\"https://spoonacular.com/recipes/sausage-and-chicken-cassoulet-197210\">Sausage-and-Chicken Cassoulet</a> for similar recipes."),
            Receta("Garlic Chicken","https://spoonacular.com/recipeImages/107878-556x370.png","http://www.epicurious.com/recipes/food/views/Garlic-Chicken-354571","Garlic Chicken might be just the main course you are searching for. One portion of this dish contains roughly <b>22g of protein</b>, <b>23g of fat</b>, and a total of <b>330 calories</b>. This caveman, gluten free, dairy free, and primal recipe serves 4 and costs <b>\$1.71 per serving</b>. Not a lot of people made this recipe, and 1 would say it hit the spot. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. If you have manzanilla sherry, chicken broth, olive oil, and a few other ingredients on hand, you can make it. All things considered, we decided this recipe <b>deserves a spoonacular score of 41%</b>. This score is solid. Try <a href=\"https://spoonacular.com/recipes/lemon-pepper-chicken-with-garlic-make-garlicky-chicken-easily-in-the-oven-599582\">Lemon Pepper Chicken with Garlic – make garlicky chicken easily in the oven</a>, <a href=\"https://spoonacular.com/recipes/honey-garlic-chicken-drumsticks-barbecue-chicken-drummettes-32023\">Honey Garlic Chicken Drumsticks (barbecue Chicken Drummettes)</a>, and <a href=\"https://spoonacular.com/recipes/garlic-oven-roasted-bone-in-skin-on-chicken-breast-aka-split-chicken-breast-574213\">Garlic Oven Roasted Bone-in Skin-on Chicken Breast (AKA Split Chicken Breast)</a> for similar recipes."),
            Receta("Chicken With Cranberries","https://spoonacular.com/recipeImages/129383-556x370.jpg","http://www.food.com/recipe/chicken-with-cranberries-368567","Chicken With Cranberries might be just the main course you are searching for. This recipe makes 4 servings with <b>241 calories</b>, <b>25g of protein</b>, and <b>9g of fat</b> each. For <b>\$1.33 per serving</b>, this recipe <b>covers 14%</b> of your daily requirements of vitamins and minerals. It will be a hit at your <b>Christmas</b> event. 1 person has made this recipe and would make it again. Head to the store and pick up pepper, salt, cranberries, and a few other things to make it today. To use up the cranberries you could follow this main course with the <a href=\"https://spoonacular.com/recipes/bread-pudding-with-dried-cranberries-128542\">Bread Pudding with Dried Cranberries</a> as a dessert. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 43%</b>. This score is good. Similar recipes include <a href=\"https://spoonacular.com/recipes/chicken-with-cranberries-129121\">Chicken with Cranberries</a>, <a href=\"https://spoonacular.com/recipes/chicken-with-cranberries-and-orange-129173\">Chicken With Cranberries and Orange</a>, and <a href=\"https://spoonacular.com/recipes/crock-pot-chicken-with-cranberries-128962\">Crock Pot Chicken With Cranberries</a>."),
            Receta("Chicken Gravy","https://spoonacular.com/recipeImages/136613-556x370.png","http://www.marthastewart.com/332664/chicken-gravy","Chicken Gravy might be just the sauce you are searching for. This recipe serves 4 and costs \$1.24 per serving. One portion of this dish contains about <b>5g of protein</b>, <b>7g of fat</b>, and a total of <b>103 calories</b>. Only a few people made this recipe, and 1 would say it hit the spot. Head to the store and pick up chicken bones and wings, chicken stock, thyme leaves, and a few other things to make it today. From preparation to the plate, this recipe takes around <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 14%</b>. This score is rather bad. Similar recipes include <a href=\"https://spoonacular.com/recipes/chicken-fried-chicken-with-country-gravy-136329\">Chicken Fried Chicken With Country Gravy</a>, <a href=\"https://spoonacular.com/recipes/southern-biscuits-and-sawmill-gravy-sausage-gravy-911801\">Southern Biscuits and Sawmill Gravy (Sausage Gravy)</a>, and <a href=\"https://spoonacular.com/recipes/chicken-gravy-598948\">Chicken Gravy</a>."),
            Receta("Andri's Chicken","https://spoonacular.com/recipeImages/136643-556x370.jpg","http://www.food.com/recipe/andris-chicken-184001","Need a <b>gluten free main course</b>? Andri's Chicken could be a tremendous recipe to try. This recipe serves 4. One portion of this dish contains approximately <b>27g of protein</b>, <b>12g of fat</b>, and a total of <b>274 calories</b>. For <b>\$2.3 per serving</b>, this recipe <b>covers 22%</b> of your daily requirements of vitamins and minerals. A mixture of butter, chicken breast, garlic powder, and a handful of other ingredients are all it takes to make this recipe so delicious. To use up the butter you could follow this main course with the <a href=\"https://spoonacular.com/recipes/cinnamon-butter-cake-60334\">Cinnamon Butter Cake</a> as a dessert. 1 person has made this recipe and would make it again. From preparation to the plate, this recipe takes around <b>30 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 58%</b>. This score is solid. Similar recipes include <a href=\"https://spoonacular.com/recipes/i-aint-chicken-chicken-crispy-roasted-chicken-breasts-with-orange-and-cardamom-310658\">I Ain't Chicken Chicken: Crispy Roasted Chicken Breasts with Orange and Cardamom</a>, <a href=\"https://spoonacular.com/recipes/the-best-shredded-chicken-for-your-chicken-dishes-+-homemade-chicken-broth-528123\">The Best Shredded Chicken For Your Chicken Dishes + Homemade Chicken Broth</a>, and <a href=\"https://spoonacular.com/recipes/popeye-tsos-chicken-general-tsos-chicken-made-with-popeyes-chicken-nuggets-196521\">Popeye Tso's Chicken (General Tso's Chicken Made with Popeye's Chicken Nuggets)</a>."),
            Receta("Chicken Saltimbocca","https://spoonacular.com/recipeImages/136858-556x370.png","http://www.marthastewart.com/339370/chicken-saltimbocca","Need a <b>gluten free, primal, and fodmap friendly main course</b>? Chicken Saltimbocca could be an awesome recipe to try. This recipe serves 4. One portion of this dish contains around <b>43g of protein</b>, <b>38g of fat</b>, and a total of <b>575 calories</b>. For <b>\$4.65 per serving</b>, this recipe <b>covers 22%</b> of your daily requirements of vitamins and minerals. 1 person has made this recipe and would make it again. Head to the store and pick up prosciutto, chicken-breast halves, madeira, and a few other things to make it today. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 47%</b>. This score is good. Similar recipes are <a href=\"https://spoonacular.com/recipes/chicken-saltimbocca-516928\">Chicken Saltimbocca</a>, <a href=\"https://spoonacular.com/recipes/chicken-saltimbocca-737598\">Chicken Saltimbocca</a>, and <a href=\"https://spoonacular.com/recipes/chicken-saltimbocca-248884\">Chicken Saltimbocca</a>."),
            Receta("Asian Chicken","https://spoonacular.com/recipeImages/143263-556x370.jpg","http://www.food.com/recipe/asian-chicken-63763","This recipe serves 4. One portion of this dish contains roughly <b>8g of protein</b>, <b>1g of fat</b>, and a total of <b>75 calories</b>. For <b>86 cents per serving</b>, this recipe <b>covers 8%</b> of your daily requirements of vitamins and minerals. 1 person has made this recipe and would make it again. A mixture of pickle juice, onions, paprika, and a handful of other ingredients are all it takes to make this recipe so yummy. From preparation to the plate, this recipe takes roughly <b>1 hour and 50 minutes</b>. It is a good option if you're following a <b>gluten free and dairy free</b> diet. All things considered, we decided this recipe <b>deserves a spoonacular score of 46%</b>. This score is good. Similar recipes include <a href=\"https://spoonacular.com/recipes/asian-chicken-burger-with-spicy-lemongrass-mayo-and-pickled-asian-slaw-295430\">Asian Chicken Burger with Spicy Lemongrass Mayo and Pickled Asian Slaw</a>, <a href=\"https://spoonacular.com/recipes/asian-chicken-632810\">Asian Chicken</a>, and <a href=\"https://spoonacular.com/recipes/ez-asian-chicken-143887\">E.z. Asian Chicken</a>.")
        )

        adapterReceta = ItemArrayAdapter(this, R.layout.lista_recetas ,datos)
        listRecipe.adapter = adapterReceta

        listRecipe.setOnItemClickListener { _, _, position, _ ->

            val receta = adapterReceta.getItem(position) ?: return@setOnItemClickListener

            val a = Intent(applicationContext, Summary::class.java)
            a.addFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT)
            a.putExtra("receta",receta)
            startActivity(a)
        }

    }
}
